	<Project Sdk="Microsoft.NET.Sdk">
		<Import Project="..\..\externals.props" Condition="Exists('..\..\externals.props')" />
		<Import Project="..\..\DimmerExternals.props" Condition="Exists('..\..\DimmerExternals.props')" />
		<Import Project="..\..\..\DimmerExternals.props" Condition="Exists('..\..\..\DimmerExternals.props')" />
		
		
		<PropertyGroup>
			<OutputType>WinExe</OutputType>
			<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
			<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
			<RootNamespace>Dimmer.WinUI</RootNamespace>
			<ApplicationManifest>app.manifest</ApplicationManifest>
			<Platforms>x86;x64;ARM64</Platforms>
			<RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
			<PublishProfile>win-$(Platform).pubxml</PublishProfile>
			<UseWinUI>true</UseWinUI>
			<EnableMsixTooling>true</EnableMsixTooling>
			<Nullable>enable</Nullable>
			<LangVersion>preview</LangVersion>
			<ImplicitUsings>enable</ImplicitUsings>
			<UseMaui>true</UseMaui>
			<!-- We do not want XAML files to be processed as .NET MAUI XAML, but rather WinUI XAML. -->
			<EnableDefaultMauiItems>false</EnableDefaultMauiItems>
			<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
			<WindowsPackageType>None</WindowsPackageType>
		
			
			<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
			<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		</PropertyGroup>

		<ItemGroup>
		  <None Remove="AppShell.xaml" />
		  <None Remove="Themes\Converters.xaml" />
		  <None Remove="Views\CustomViews\MauiViews\SyncLyricsPopUpViewWindow.xaml" />
		  <None Remove="Views\CustomViews\WinuiViews\ArcFabControl.xaml" />
		  <None Remove="Views\CustomViews\WinuiViews\HoverCardControl.xaml" />
		  <None Remove="Views\CustomViews\WinuiViews\MediaPlaybackSection.xaml" />
		  <None Remove="Views\CustomViews\WinuiViews\MorphContainerView.xaml" />
		  <None Remove="Views\CustomViews\WinuiViews\NativeLyricsOverlayWindow.xaml" />
		  <None Remove="Views\CustomViews\WinuiViews\SearchHelpDialog.xaml" />
		  <None Remove="Views\CustomViews\WinuiViews\SingleSongDetailsPopupView.xaml" />
		  <None Remove="Views\CustomViews\WinuiViews\SingleSongSection\ChangesReviewPopup.xaml" />
		  <None Remove="Views\CustomViews\WinuiViews\SmokeViewQueueGrid.xaml" />
		  <None Remove="Views\CustomViews\WinuiViews\SongLyricsView.xaml" />
		  <None Remove="Views\CustomViews\WinuiViews\SongMetadataView.xaml" />
		  <None Remove="Views\CustomViews\WinuiViews\SongStatsView.xaml" />
		  <None Remove="Views\CustomViews\WinuiViews\VolumeTab.xaml" />
		  <None Remove="Views\WinuiPages\Achievements\GlobalAchievementsPage.xaml" />
		  <None Remove="Views\WinuiPages\Achievements\SongAchievementsControl.xaml" />
		  <None Remove="Views\WinuiPages\AlbumPage.xaml" />
		  <None Remove="Views\WinuiPages\AlbumSection\AlbumsStats.xaml" />
		  <None Remove="Views\WinuiPages\AlbumSection\AllAlbumsPage.xaml" />
		  <None Remove="Views\WinuiPages\AllSongsListPage.xaml" />
		  <None Remove="Views\WinuiPages\ArtistPage.xaml" />
		  <None Remove="Views\WinuiPages\Artist\AllArtistsPage.xaml" />
		  <None Remove="Views\WinuiPages\Artist\ArtistDetailsPage.xaml" />
		  <None Remove="Views\WinuiPages\Artist\ArtistsOverViewPage.xaml" />
		  <None Remove="Views\WinuiPages\AudioEditorPage.xaml" />
		  <None Remove="Views\WinuiPages\DimmerLivePage.xaml" />
		  <None Remove="Views\WinuiPages\DimmerLive\AppUpdateCenter.xaml" />
		  <None Remove="Views\WinuiPages\DimmerLive\CloudDataPage.xaml" />
		  <None Remove="Views\WinuiPages\DimmerLive\LoginPage.xaml" />
		  <None Remove="Views\WinuiPages\DimmerLive\ProfilePage.xaml" />
		  <None Remove="Views\WinuiPages\DimmerLive\RemoteControlPage.xaml" />
		  <None Remove="Views\WinuiPages\DimmerLive\SocialPage.xaml" />
		  <None Remove="Views\WinuiPages\DimmsSection\AllDimsView.xaml" />
		  <None Remove="Views\WinuiPages\LastFMSection\LastFmPage.xaml" />
		  <None Remove="Views\WinuiPages\PlaylistSection\AllPlaylistsPage.xaml" />
		  <None Remove="Views\WinuiPages\PlaylistSection\SinglePlaylistPage.xaml" />
		  <None Remove="Views\WinuiPages\SettingsPage.xaml" />
		  <None Remove="Views\WinuiPages\Settings\AppUtilsPage.xaml" />
		  <None Remove="Views\WinuiPages\Settings\FoldersSettingsPage.xaml" />
		  <None Remove="Views\WinuiPages\Settings\RestorePage.xaml" />
		  <None Remove="Views\WinuiPages\SingleSongPage\EditSongPage.xaml" />
		  <None Remove="Views\WinuiPages\SingleSongPage\SingleSongLyrics.xaml" />
		  <None Remove="Views\WinuiPages\SingleSongPage\SongStatsContainerPage.xaml" />
		  <None Remove="Views\WinuiPages\SingleSongPage\SubPage\LyricsManualSyncPage.xaml" />
		  <None Remove="Views\WinuiPages\SingleSongPage\SubPage\LyricsOverViewPage.xaml" />
		  <None Remove="Views\WinuiPages\SingleSongPage\SubPage\OnlineLyricsSearchPage.xaml" />
		  <None Remove="Views\WinuiPages\SingleSongPage\SubPage\Stats\SongArtistStatsPage.xaml" />
		  <None Remove="Views\WinuiPages\SingleSongPage\SubPage\Stats\SongJourneyPage.xaml" />
		  <None Remove="Views\WinuiPages\SongDetailPage.xaml" />
		  <None Remove="Views\WinuiPages\Utilities\DimmerToolKit.xaml" />
		  <None Remove="Views\WinuiPages\Wrapped\WrappedContainerPage.xaml" />
		  <None Remove="Views\WinuiPages\Wrapped\WrappedSummaryView.xaml" />
		  <None Remove="Views\WinuiPages\Wrapped\WrappedTopArtistView.xaml" />
		  <None Remove="Views\WinuiPages\Wrapped\WrappedTopSongView.xaml" />
		</ItemGroup>

		<ItemGroup>
		  <Page Remove="AppShell.xaml" />
		  <Page Remove="Views\CustomViews\MauiViews\SyncLyricsPopUpViewWindow.xaml" />
		  <Page Remove="Views\MAUIPages\HomePage.xaml" />
		</ItemGroup>
		<PropertyGroup Condition="'$(TargetFramework)'=='net10.0-windows10.0.19041.0'">
			<DefineConstants>WINDOWS</DefineConstants>
		</PropertyGroup>


		<PropertyGroup>
			<!-- Silences the version constraint warning -->
			<NoWarn>$(NoWarn);NU1608</NoWarn>
		</PropertyGroup>
		
		<ItemGroup>
			
			<PackageReference Include="DevWinUI" Version="10.6.0" />
			
			<PackageReference Include="LiveChartsCore.SkiaSharpView.WinUI" Version="2.0.5" />

			<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.110" />
			<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.12" />

			<!--<PackageReference Include="DevWinUI" Version="10.4.2" />
			<PackageReference Include="DevWinUI.ContextMenu" Version="10.0.0" />-->
			
			<!--<PackageReference Include="DevWinUI.SourceGenerator" Version="10.2.0" />-->
			<PackageReference Include="CommunityToolkit.WinUI.Animations" Version="8.2.251219" />
			<PackageReference Include="CommunityToolkit.WinUI.Extensions" Version="8.2.251219" />
			<PackageReference Include="CommunityToolkit.WinUI.Helpers" Version="8.2.251219" />
			<!--<PackageReference Include="Microsoft.WindowsAppSDK.Base" Version="1.8.251216001" />-->
			<!--<PackageReference Include="Microsoft.WindowsAppSDK.Base" Version="2.0.4" />-->
			<PackageReference Include="CommunityToolkit.WinUI.UI.Controls.DataGrid" Version="7.1.2" />
			<PackageReference Include="Microsoft.WindowsAppSDK.InteractiveExperiences" Version="2.1.9" />
			<PackageReference Include="Microsoft.WindowsAppSDK.WinUI" Version="2.3.9" />
			<PackageReference Include="SkiaSharp.HarfBuzz" Version="4.153.1" />
			<PackageReference Include="WinUI.TableView" Version="1.5.0" />
			<PackageReference Include="Microsoft.WindowsAppSDK.Foundation" Version="2.3.12" />
			
			<!--<PackageReference Include="Microsoft.WindowsAppSDK.Base" Version="2.0.4" />-->
		</ItemGroup>
		
		<ItemGroup>
			<!--<ProjectReference Include="..\..\..\YBTopaz8\DevWinUI-main\dev\DevWinUI\DevWinUI.csproj" />-->
			<!--<ProjectReference Include="..\..\..\YBTopaz8\DevWinUI-main\dev\DevWinUI.ContextMenu\DevWinUI.ContextMenu.csproj" />-->
			<ProjectReference Include="..\Dimmer\Dimmer.csproj" />
		</ItemGroup>
	
		<ItemGroup>
			<!-- Make sure all image assets to be in the root of the package to match the other platforms -->
			<Content Update="Assets\Images\*" TargetPath="%(Filename)%(Extension)" />
		</ItemGroup>

		
		
		<!--<ItemGroup>
		  <MauiXaml Include="AppShell.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </MauiXaml>
		  <MauiXaml Include="Views\CustomViews\MauiViews\SyncLyricsPopUpViewWindow.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </MauiXaml>
		  <MauiXaml Include="Views\MAUIPages\HomePage.xaml" />
		 
		</ItemGroup>-->

		<ItemGroup>
		  <MauiXaml Include="AppShell.xaml" />
		  <MauiXaml Include="Views\CustomViews\MauiViews\SyncLyricsPopUpViewWindow.xaml" />
		  <MauiXaml Include="Views\MAUIPages\HomePage.xaml" />
		</ItemGroup>
		
		<ItemGroup>
		  <Page Update="Views\CustomViews\WinuiViews\NativeLyricsOverlayWindow.xaml">
		    <Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
	
		
		<ItemGroup>
		  <Page Update="Views\WinuiPages\Artist\ArtistDetailsPage.xaml">
		    <Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\Settings\RestorePage.xaml">
		    <Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\Settings\AppUtilsPage.xaml">
		    <Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\PlaylistSection\SinglePlaylistPage.xaml">
		    <Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\PlaylistSection\AllPlaylistsPage.xaml">
		    <Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\DimmerLive\RemoteControlPage.xaml">
		    <Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\Settings\FoldersSettingsPage.xaml">
		    <Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\Utilities\DimmerToolKit.xaml">
		    <Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\AlbumSection\AllAlbumsPage.xaml">
		    <Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\Artist\ArtistsOverViewPage.xaml">
		    <Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\Artist\AllArtistsPage.xaml">
		    <Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\Settings\BackupPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\CustomViews\WinuiViews\SingleSongSection\ChangesReviewPopup.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\DimmerLive\AppUpdateCenter.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\CustomViews\WinuiViews\SingleSongDetailsPopupView.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\CustomViews\WinuiViews\ArcFabControl.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\CustomViews\WinuiViews\SmokeViewQueueGrid.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\CustomViews\WinuiViews\SearchHelpDialog.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\SingleSongPage\SubPage\LyricsManualSyncPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\Achievements\SongAchievementsControl.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\Achievements\GlobalAchievementsPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\AlbumSection\AlbumsStats.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\LastFMSection\LastFmPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\DimmerLive\ProfilePage.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\DimmerLive\LoginPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\DimmerLive\SocialPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\DimmerLive\CloudDataPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\CustomViews\WinuiViews\MorphContainerView.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\AudioEditorPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\Wrapped\WrappedContainerPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\Wrapped\WrappedSummaryView.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\Wrapped\WrappedTopArtistView.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\Wrapped\WrappedTopSongView.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\DimmsSection\AllDimsView.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\SingleSongPage\SubPage\Stats\SongJourneyPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\SingleSongPage\SubPage\Stats\SongArtistStatsPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\SingleSongPage\SubPage\Stats\SongOverviewStatsPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\SingleSongPage\SongStatsContainerPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\SingleSongPage\SubPage\OnlineLyricsSearchPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\SingleSongPage\SubPage\LyricsOverViewPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\SingleSongPage\SingleSongLyrics.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\SingleSongPage\EditSongPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\DimmerLivePage.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\CustomViews\WinuiViews\SongLyricsView.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\CustomViews\WinuiViews\SongMetadataView.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\CustomViews\WinuiViews\SongStatsView.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\CustomViews\WinuiViews\MediaPlaybackSection.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\CustomViews\WinuiViews\AudioDeviceListTab.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\CustomViews\WinuiViews\VolumeTab.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\SettingsPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\AlbumPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\ArtistPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\SongDetailPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\WinuiPages\AllSongsListPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Views\CustomViews\WinuiViews\HoverCardControl.xaml">
			<Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>
		<ItemGroup>
		  <Page Update="Themes\Converters.xaml">
		    <Generator>MSBuild:Compile</Generator>
		  </Page>
		</ItemGroup>

		
		

	</Project>
