//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dimmer.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DimmerLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DimmerLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dimmer.Resources.Localization.DimmerLanguage", typeof(DimmerLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string btnprofiletxt {
            get {
                return ResourceManager.GetString("btnprofiletxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To Dimmer !.
        /// </summary>
        public static string gettingstart_txt_wlc {
            get {
                return ResourceManager.GetString("gettingstart_txt_wlc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string next_btn {
            get {
                return ResourceManager.GetString("next_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        public static string txt_addfolder {
            get {
                return ResourceManager.GetString("txt_addfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string txt_album {
            get {
                return ResourceManager.GetString("txt_album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string txt_artist {
            get {
                return ResourceManager.GetString("txt_artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string txt_backup {
            get {
                return ResourceManager.GetString("txt_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string txt_cancel {
            get {
                return ResourceManager.GetString("txt_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string txt_close {
            get {
                return ResourceManager.GetString("txt_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string txt_confirm {
            get {
                return ResourceManager.GetString("txt_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string txt_continue {
            get {
                return ResourceManager.GetString("txt_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string txt_delete {
            get {
                return ResourceManager.GetString("txt_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string txt_edit {
            get {
                return ResourceManager.GetString("txt_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string txt_email {
            get {
                return ResourceManager.GetString("txt_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        public static string txt_explore {
            get {
                return ResourceManager.GetString("txt_explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string txt_favorites {
            get {
                return ResourceManager.GetString("txt_favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string txt_folder {
            get {
                return ResourceManager.GetString("txt_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossiers.
        /// </summary>
        public static string txt_folders {
            get {
                return ResourceManager.GetString("txt_folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten Password.
        /// </summary>
        public static string txt_forgottenpass {
            get {
                return ResourceManager.GetString("txt_forgottenpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string txt_hello {
            get {
                return ResourceManager.GetString("txt_hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string txt_home {
            get {
                return ResourceManager.GetString("txt_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string txt_login {
            get {
                return ResourceManager.GetString("txt_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string txt_logout {
            get {
                return ResourceManager.GetString("txt_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string txt_minimize {
            get {
                return ResourceManager.GetString("txt_minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string txt_next {
            get {
                return ResourceManager.GetString("txt_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string txt_No {
            get {
                return ResourceManager.GetString("txt_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string txt_Note {
            get {
                return ResourceManager.GetString("txt_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing Yet ! (Hello 🤗).
        /// </summary>
        public static string txt_nothingyet {
            get {
                return ResourceManager.GetString("txt_nothingyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string txt_pass {
            get {
                return ResourceManager.GetString("txt_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string txt_pause {
            get {
                return ResourceManager.GetString("txt_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string txt_play {
            get {
                return ResourceManager.GetString("txt_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string txt_previous {
            get {
                return ResourceManager.GetString("txt_previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string txt_remove {
            get {
                return ResourceManager.GetString("txt_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string txt_repeat {
            get {
                return ResourceManager.GetString("txt_repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string txt_restore {
            get {
                return ResourceManager.GetString("txt_restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string txt_scan {
            get {
                return ResourceManager.GetString("txt_scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folders.
        /// </summary>
        public static string txt_selectfolders {
            get {
                return ResourceManager.GetString("txt_selectfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string txt_send {
            get {
                return ResourceManager.GetString("txt_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string txt_signup {
            get {
                return ResourceManager.GetString("txt_signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string txt_statististics {
            get {
                return ResourceManager.GetString("txt_statististics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        public static string txt_stats {
            get {
                return ResourceManager.GetString("txt_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string txt_stop {
            get {
                return ResourceManager.GetString("txt_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize.
        /// </summary>
        public static string txt_sync {
            get {
                return ResourceManager.GetString("txt_sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string txt_username {
            get {
                return ResourceManager.GetString("txt_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility.
        /// </summary>
        public static string txt_utility {
            get {
                return ResourceManager.GetString("txt_utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string txt_view {
            get {
                return ResourceManager.GetString("txt_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View More.
        /// </summary>
        public static string txt_viewmore {
            get {
                return ResourceManager.GetString("txt_viewmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string txt_Yes {
            get {
                return ResourceManager.GetString("txt_Yes", resourceCulture);
            }
        }
    }
}
