name: Discord Release and Push Notifier

on:
  release:
    types: [published]
  push:
    branches:
      - Dev-Official
      - master

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (for push and release events)
        uses: actions/checkout@v4 # Checkout is needed for generating the tag

      - name: Generate Tag Name
        if: github.event_name == 'release' # Only generate tag on release
        id: generate_tag
        run: |
          echo "tag=$(date +'%d-%m-%Y_%H-%M-%S')" >> $GITHUB_OUTPUT  # Correct date format


      - name: Send Discord Notification (Release)
        if: github.event_name == 'release'
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            New release ${{ steps.generate_tag.outputs.tag }} of Dimmer is now available!
            This is a test release body.
            Release URL: https://example.com # Replace with actual logic to get URL if needed

      - name: Send Discord Notification (Push)
        if: github.event_name == 'push'
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            New push to ${{ github.ref_name }} branch in Dimmer!
            Commit message: ${{ github.event.head_commit.message }}
            Committer: ${{ github.event.head_commit.author.name }}
            Commit URL: ${{ github.event.head_commit.url }}
            Pushed by: ${{ github.actor }}
