name: Dimmer Release and Push Notifier

on:
  release:
    types: [published]
  push:
    branches:
      - Dev-Official
      - master

jobs:
  notify_back4app:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Release Tag (Release Event)
        if: github.event_name == 'release'
        id: get_release_tag
        run: echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT

      - name: Set Release URL (Release Event)
        if: github.event_name == 'release'
        id: get_release_url
        run: echo "release_url=${{ github.event.release.html_url }}" >> $GITHUB_OUTPUT

      - name: Print Secrets (for Debugging)
        run: |
          echo "BACK4APP_WEBHOOK_URL: ${{ secrets.BACK4APP_WEBHOOK_URL }}"
          echo "PARSE_APP_ID: ${{ secrets.PARSE_APP_ID }}"
          echo "PARSE_REST_API_KEY: ${{ secrets.PARSE_REST_API_KEY }}"
          echo "BACK4APP_WEBHOOK_KEY: ${{ secrets.BACK4APP_WEBHOOK_KEY }}"

      - name: Send Back4App Webhook (Release or Push)
        run: |
          commit_message=$(echo '${{ toJSON(github.event.head_commit.message) }}' | tr -d '"')
          commit_url=$(echo '${{ toJSON(github.event.head_commit.url) }}' | tr -d '"')

          payload=$(cat << EOF
          {
            "master": false,
            "installationId": "",
            "params": {
              "commitMessage": "${commit_message}",
              "commitUrl": "${commit_url}",
              "branch": "${{ github.ref_name }}",
              "pusher": "${{ github.actor }}",
              "releaseTag": "${{ steps.get_release_tag.outputs.tag }}",
              "releaseUrl": "${{ steps.get_release_url.outputs.release_url }}"
            },
            "functionName": "githubUpdate"
          }
          EOF
          )
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-Parse-Application-Id: ${{ secrets.PARSE_APP_ID }}" \
            -H "X-Parse-REST-API-Key: ${{ secrets.PARSE_REST_API_KEY }}" \
            -H "X-Parse-Webhook-Key: ${{ secrets.BACK4APP_WEBHOOK_KEY }}" \
            -d "$payload" \
            "${{ secrets.BACK4APP_WEBHOOK_URL }}"
